ecommerce/basket/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'basket'

urlpatterns = [
    path('',basket_list,name="basket_list"),
    path('addTo_basket/<int:pk>/',addTo_basket),
    path('basketdetail/<int:pk>/',basket_details),
    path('basket_delete/<int:pk>/',basket_delete),
]

ecommerce/customer/urls.py
from django.urls import path
from .views import  customer_details, customer_list, customer_delete
from django.conf import settings
from django.conf.urls.static import static

app_name = 'customer'

urlpatterns = [
    path('',customer_list,name="customer_list"),
    path('customer_delete/<int:pk>/',customer_delete,name="customer_delete"),
    path('customer_detail/<int:pk>/',customer_details,name="customer_details"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecommerce/home/urls.py
from django.urls import path
from .views import  home
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',home,name="home")
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecommerce/product/urls.py
from django.urls import path
from .views import  *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'product'

urlpatterns = [
    path('',product_list,name="product_list"),
    path('product_delete/<int:pk>/',product_delete,name="product_delete"),
    path('product_edit/<int:pk>/', product_edit,name="product_edit"),  
    path('product_update/<int:pk>/', product_update,name="product_update"),  
    path('product_detail/<int:pk>/',product_details,name="product_details"),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecommerce/basket/models.py
from django.db import models
from customer.models import Customer
from product.models import Product

# Create your models here.
class Basket(models.Model):
     id = models.IntegerField(primary_key=True)
     customer_id = models.ForeignKey(Customer,on_delete=models.CASCADE)
     product_id = models.ForeignKey(Product,on_delete=models.CASCADE)
     quantity = models.IntegerField(null=False)
     created_date = models.DateTimeField(auto_now=False, auto_now_add=False)
     active = models.BooleanField(default=True)

ecommerce/customer/models.py
from django.db import models

# Create your models here.
class Customer(models.Model):
    id = models.IntegerField(primary_key=True)
    fullname = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    mobile = models.CharField(max_length=15)
    address = models.CharField(max_length=100)

ecommerce/home/models.py
from django.db import models

# Create your models here.

ecommerce/product/models.py
from django.db import models


# Create your models here.
class Product(models.Model):
     product_name = models.CharField(max_length=100)
     product_id = models.IntegerField(primary_key=True)
     description = models.CharField(max_length=100)
     price = models.IntegerField(null=False)
     created_date = models.DateTimeField(auto_now=False, auto_now_add=False)

ecommerce/basket/views.py
import datetime
from product.models import Product
from customer.models import Customer
from django.shortcuts import redirect, render
from django.http import HttpResponse,JsonResponse, response
from rest_framework.parsers import JSONParser
from .models import Basket
from .serializer import BasketSerializer 
from rest_framework.decorators import api_view
from rest_framework.response import Response, responses
from rest_framework import status
# Create your views here.

@api_view(['GET','POST'])
def basket_list(request):
    if request.method == 'GET':
        basket = Basket.objects.all()
        serializer = BasketSerializer(basket,many=True)
        return render(request, 'basket.html', {'basket':basket})
    elif request.method == 'POST':
        serializer = BasketSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data,status=status.HTTP_201_CREATED)
        return Response(serializer.errors,status=status.HTTP_400_BAD_REQUEST)

@api_view(['GET','PUT','DELETE'])
def basket_details(request,pk):
    try:
        basket = Basket.objects.get(pk=pk)
    except Basket.DoesNotExist:
        return HttpResponse(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = BasketSerializer(basket)
        return Response(serializer.data)
    elif request.method == 'PUT':
        serializer = BasketSerializer(basket,data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors,status=status.HTTP_400_BAD_REQUEST)
    elif request.method == 'DELETE':
        basket.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

def addTo_basket(request,pk):
    customer = Customer.objects.get(pk=1)
    product = Product.objects.get(pk=pk)
    basket = Basket()
    basket.customer_id=customer
    basket.product_id=product
    basket.created_date=datetime.datetime.now()
    basket.quantity=1
    basket.save()
    return redirect("home")  

def basket_delete(request,pk):
    try:
        basket = Basket.objects.get(pk=pk)

    except Product.DoesNotExist:
        return HttpResponse(status=status.HTTP_404_NOT_FOUND)
    basket.delete()
    basket = Basket.objects.all()
    return redirect("/basket/") 
    # return render(request, 'basket.html', {'basket':basket})  

ecommerce/customer/views.py
from customer.form import Customerform
from django.shortcuts import redirect, render
from django.http import HttpResponse,JsonResponse, response
from rest_framework.parsers import JSONParser
from .models import Customer
from .serializer import CustomerSerializer 
from rest_framework.decorators import api_view
from rest_framework.response import Response, responses
from rest_framework import status
# Create your views here.

@api_view(['GET','POST'])
def customer_list(request):
    cust=Customerform(request.POST, request.FILES)
    if request.method == 'GET':
        if cust.is_valid():
            cust.save()

        customers = Customer.objects.all()
        serializer = CustomerSerializer(customers,many=True)
        # return Response(serializer.data)
        context = {'cust':cust, 'customers':customers}
        return render(request, 'customers.html', context)
    elif request.method == 'POST':
        serializer = CustomerSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            customers = Customer.objects.all()
            return render(request, 'customers.html', {'cust':cust, 'customers':customers})
        return Response(serializer.errors,status=status.HTTP_400_BAD_REQUEST)

@api_view(['GET','PUT','DELETE'])
def customer_details(request,pk):
    try:
        customer = Customer.objects.get(pk=pk)
    except Customer.DoesNotExist:
        return HttpResponse(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = CustomerSerializer(customer)
        return Response(serializer.data)
    elif request.method == 'PUT':
        serializer = CustomerSerializer(customer,data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors,status=status.HTTP_400_BAD_REQUEST)


def customer_delete(request,pk):
    try:
        product = Customer.objects.get(pk=pk)

    except Customer.DoesNotExist:
        return HttpResponse(status=status.HTTP_404_NOT_FOUND)
    product.delete()
    prod=Customerform(request.POST, request.FILES)
    products = Customer.objects.all()
    return redirect("/customer/")  

ecommerce/home/views.py
from django.shortcuts import render,redirect
from rest_framework.decorators import api_view
from rest_framework.response import Response, responses
from product.models import Product

# Create your views here.

@api_view(['GET','POST'])
def home(request):
    products = Product.objects.all()
    return render(request, 'home.html', {'products': products})

ecommerce/product/views.py
from product.form import Productform
from django.shortcuts import render,redirect  
from django.http import HttpResponse,JsonResponse
from rest_framework import serializers
from rest_framework.parsers import JSONParser
from .models import Product
from .serializer import ProductSerializer
from django.views.decorators.csrf import csrf_exempt
from rest_framework.decorators import api_view
from rest_framework.response import Response, responses
from rest_framework import status
from rest_framework.views import APIView

@api_view(['GET','POST'])
def product_list(request):
    prod=Productform(request.POST, request.FILES)
    if request.method == 'GET':
        if prod.is_valid():
            prod.save()

        products = Product.objects.all()
        serializer = ProductSerializer(products,many=True)
        #return Response(serializer.data)
        context = {'prod':prod, 'products':products}
        return render(request, 'product.html', context)
    elif request.method == 'POST':
        serializer = ProductSerializer(data=request.data)

        if serializer.is_valid():
            serializer.save()
            products = Product.objects.all()
            return render(request, 'product.html', {'prod':prod, 'products':products})
        return Response(serializer.errors,status=status.HTTP_400_BAD_REQUEST)

@api_view(['GET','PUT'])
def product_details(request,pk):
    try:
        product = Product.objects.get(pk=pk)

    except Product.DoesNotExist:
        return HttpResponse(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = ProductSerializer(product)
        return Response(serializer.data)
    elif request.method == 'PUT':
        serializer = ProductSerializer(product,data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors,status=status.HTTP_400_BAD_REQUEST)

def product_delete(request,pk):
    try:
        product = Product.objects.get(pk=pk)

    except Product.DoesNotExist:
        return HttpResponse(status=status.HTTP_404_NOT_FOUND)
    product.delete()
    prod=Productform(request.POST, request.FILES)
    products = Product.objects.all()
    return redirect("/product/")  

def product_edit(request, pk):  
    product = Product.objects.get(pk=pk)
    return render(request,'edit_product.html', {'product':product})  

def product_update(request, pk):
    product = Product.objects.get(pk=pk)  
    print(request.POST)
    form = Productform(request.POST, instance = product)  
    if form.is_valid():  
        form.save()  
        return redirect("/product/")  
    # return render(request, 'edit_product.html', {'product': product})  
    return redirect("/product/")





    # try:
    #     product = Product.objects.get(pk=pk)

    # except Product.DoesNotExist:
    #     return HttpResponse(status=status.HTTP_404_NOT_FOUND)
    # serializer = ProductSerializer(product,data=request.data)
    # if serializer.is_valid():
    #     serializer.save()
    #     render(request,'product.html', {'product':product})
    # return Response(serializer.errors,status=status.HTTP_400_BAD_REQUEST)

ecommerce/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}Store{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous">
    </script>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">Store</a>
                <a class="navbar-brand" style="font-size: smaller;" href="{% url 'product:product_list' %}">Add Products</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" style="font-size: smaller;" href="{% url 'customer:customer_list' %}">Add Customer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse" style="margin-left: 75%;">
                    <a type="button" role="button" href="{% url 'basket:basket_list' %}"
                        class="btn btn-outline-secondary">
                        {% with total_qty=basket|length %}
                            <div id="basket-qty" class="d-inline-flex">
                                {% if total_qty > 0 %}
                                    {{ total_qty }}
                                {% else %}
                                    0
                                {% endif %}
                            </div>
                        {% endwith %} 

                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                            class="bi bi-cart3" viewBox="0 0 16 16">
                            <path
                                d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                        </svg>
                        Basket
                    </a>
                </div>
            </div>
        </nav>
    </header>
    <div id="content">{% block content %} {% endblock %}</div>
</body>

</html>

ecommerce/templates/basket.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Store{% endblock %}
{% block content %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Product Dashboard</title>
  </head>
  <body>
    <div class="col-lg-12">
    <div class="container">
    <div class="row">
    <div class="col-lg-12">
    <div class="row">
      {% load crispy_forms_tags %}
    <div class="col-lg-12">
    <div class="container">
    <div class="row">
    <div class="col-lg-6 mx-auto forms">
    </div>
    </div>
    </div>
    </div>
    </div>
    <div class="row">
    <div class="col-lg-12 text-center mt-5">
    <h4>Basket Information</h4> <br>
    </div>
    <div class="col-lg-6 mt-5 mb-5">
    


      
    </div>
    <div class="col-lg-6">

    </div>
    </div>
    </div>
    <table class="table table-hover" style="height:300px; overflow-y:scroll; border-bottom:2px blue solid;">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">customer_id</th>
      <th scope="col">product_id</th>
      <th scope="col">quantity</th>
      <th scope="col">created_date</th>
      <th scope="col">Delete</th>

    </tr>
  </thead>
  <tbody>
    {% for i in basket %}
    <tr>
      <th scope="row">{{i.id}}</th>
      <td>{{i.customer_id}}</td>
      <td>{{i.product_id}}</td>
      <td>{{i.quantity}}</td>
      <td>{{i.created_date}}</td>
      <td>
        <a href="basket_delete/{{ i.id }}/">Delete</a>  
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
    </div>
    </div>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

{% endblock %}

ecommerce/templates/customers.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Store{% endblock %}
{% block content %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Customer Dashboard</title>
  </head>
  <body>
    <div class="col-lg-12">
    <div class="container">
    <div class="row">
    <div class="col-lg-12">
    <div class="row">
      {% load crispy_forms_tags %}
    <div class="col-lg-12">
    <div class="container">
    <div class="row">
    <div class="col-lg-12 text-center">
    <h4>Add Customer Information</h4> <br>
    </div>
    <div class="col-lg-6 mx-auto forms">
    <form action="." method="post">
    {% csrf_token %}
    {{cust|crispy}}
    <button class="btn btn-primary" type="submit">Add Customer</button>
    </form>
    </div>
    </div>
    </div>
    </div>
    </div>
    <div class="row">
    <div class="col-lg-12 text-center mt-5">
    <h4>Customer Information</h4> <br>
    </div>
    <div class="col-lg-6 mt-5 mb-5">
    


      
    </div>
    <div class="col-lg-6">

    </div>
    </div>
    </div>
    <table class="table table-hover" style="height:300px; overflow-y:scroll; border-bottom:2px blue solid;">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">fullname</th>
      <th scope="col">email</th>
      <th scope="col">mobile</th>
      <th scope="col">address</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
      <!-- <th scope="col">Edit</th> -->

    </tr>
  </thead>
  <tbody>
    {% for i in customers %}
    <tr>
      <th scope="row">{{i.id}}</th>
      <td>{{i.fullname}}</td>
      <td>{{i.email}}</td>
      <td>{{i.mobile}}</td>
      <td>{{i.address}}</td>
      <td><button type="button" class="btn btn-primary">
        <i class="fa fa-edit" aria-hidden="true"></i> Edit</button>
      </td>
      <td>
      <a href="customer_delete/{{ i.id }}/">Delete</a> 
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
    </div>
    </div>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>
{% endblock %}

ecommerce/templates/edit_product.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Store{% endblock %}
{% block content %}
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Edit Product</title>
</head>  
<body>  
<form method="POST" class="post-form" action="/product/product_update/{{product.product_id}}/">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Product Id:</label>  
    <div class="col-sm-4">  
        <input type="number" name="product_id" id="id_product_id" required maxlength="20" value="{{ product.product_id }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Product Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="product_name" id="id_product_name" required maxlength="100" value="{{ product.product_name }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Product description:</label>  
    <div class="col-sm-4">  
        <input type="text" name="description" id="id_description" required maxlength="500" value="{{ product.description }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Price:</label>  
    <div class="col-sm-4">  
        <input type="number" name="price" id="id_price" required maxlength="15" value="{{ product.price }}" />  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Created Date:</label>  
    <div class="col-sm-4">  
        <input type="datetime" name="created_date" id="id_created_date" value="{{ product.created_date }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  
{% endblock %}

ecommerce/templates/home.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Store{% endblock %}
{% block content %}


<main>
  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">All Products</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for product in products %}

        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" >{{ product.product_name }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                Product Price :<span class="text-muted" style="font-weight: bold;margin-right: 25%;">{{ product.price }}</span>
              </div>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">{{ product.description }}</small>
              </div>
              <div class="d-flex justify-content-between align-items-center">
                <a href="basket/addTo_basket/{{ product.product_id }}/">Add to Basket</a> 
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock %}

ecommerce/templates/product.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Store{% endblock %}
{% block content %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Product Dashboard</title>
  </head>
  <body>
    <div class="col-lg-12">
    <div class="container">
    <div class="row">
    <div class="col-lg-12">
    <div class="row">
      {% load crispy_forms_tags %}
    <div class="col-lg-12">
    <div class="container">
    <div class="row">
    <div class="col-lg-12 text-center">
    <h4>Add Product Information</h4> <br>
    </div>
    <div class="col-lg-6 mx-auto forms">
    <form action="." method="post">
    {% csrf_token %}
    {{prod|crispy}}
    <button class="btn btn-primary" type="submit">Add Product</button>
    </form>
    </div>
    </div>
    </div>
    </div>
    </div>
    <div class="row">
    <div class="col-lg-12 text-center mt-5">
    <h4>Product Information</h4> <br>
    </div>
    <div class="col-lg-6 mt-5 mb-5">
    


      
    </div>
    <div class="col-lg-6">

    </div>
    </div>
    </div>
    <table class="table table-hover" style="height:300px; overflow-y:scroll; border-bottom:2px blue solid;">
  <thead>
    <tr>
      <th scope="col">product_id</th>
      <th scope="col">product_name</th>
      <th scope="col">description</th>
      <th scope="col">price</th>
      <th scope="col">created_date</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>

    </tr>
  </thead>
  <tbody>
    {% for i in products %}
    <tr>
      <th scope="row">{{i.product_id}}</th>
      <td>{{i.product_name}}</td>
      <td>{{i.description}}</td>
      <td>{{i.price}}</td>
      <td>{{i.created_date}}</td>
      <td>
        <a href="product_edit/{{ i.product_id }}">Edit</span></a>  
      </td>
      <td>
        <a href="product_delete/{{ i.product_id }}/">Delete</a>  
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
    </div>
    </div>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

{% endblock %}